objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CBCreateAccountService.cls
@RestResource(urlMapping='/createAccount/*')
global with sharing class CBCreateAccountService {
  @HttpPost
    global static String createAccount(String name, String sfdcId) {
        System.debug('------EP');
        Account account = new Account();
        account.Name = name;
        account.Active__c  = 'true';
        account.Salesforce_Id__c = sfdcId;    
        insert account;
        return account.Id;
    }
}