objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CBActivateAccountService.cls
@RestResource(urlMapping='/activateAccount/*')
global with sharing class CBActivateAccountService {
     @HttpPost
    global static String activateAccount(String sfdcId) {
        Account account = new Account();
        account.Salesforce_Id__c  = sfdcId;
        account.Active__c = 'true';
        try {
        	update account;
            return 'sucess';
        } Catch (Exception ex) {
            return ex.getMessage();
        }
    }
}